=== RedEarListeningWind/MyGreedySnake/src/My.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="书架" >

        <xs:complexType>
            <xs:sequence>
                <xs:element name="书" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="书名" type="xs:string"/>
                            <xs:element name="作者" type="xs:string"/>
                            <xs:element name="单价" type="xs:integer"/>
                        </xs:sequence>
                        <xs:attribute name="页数" type="xs:integer"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== RedEarListeningWind/MyGreedySnake/src/My.xml
<?xml version="1.0" encoding="UTF-8"?>
<xs:书架 xmlns="http://www.w3school.com.cn"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:xs="file://D:/Learn/Java/GreedySnake/src/My.xsd"
    xsi:schemaLocation="http://www.w3school.com.cn
                        My.xsd">
    <xs:书 页数="366">

        <xs:书名>jhglie</xs:书名>
        <xs:作者>2541</xs:作者>
        <xs:单价>23</xs:单价>
    </xs:书>
    <xs:书 页数="355">

        <xs:书名>jhglie</xs:书名>
        <xs:作者>2541</xs:作者>
        <xs:单价>21</xs:单价>
    </xs:书>

</xs:书架>
